<!DOCTYPE html>
<html>
    <head><?php include 'app/theme/header.phtml' ?></head>
    <body>
        <article class="container">
            <?php include 'app/theme/navigation.phtml' ?>
            <?php include 'app/theme/branding.phtml' ?>
            <h2>Books results</h2>
            <table class="table table-striped table-bordered table-hover">
                <tr><th colspan="2">Title</th></tr>
            <?php foreach($books as $book) : ?>
                <tr>
                    <td><?php echo htmlspecialchars($book['title'], ENT_QUOTES, 'UTF-8') ?></td>
                    <td>
                        <a href="/index.php/books/<?php echo (integer) $book['book_id'] ?>">
                            Read now
                        </a>
                    </td>
                <tr>
            <?php endforeach ?>
            </table>
        </article>
        <?php include 'app/theme/scripts.phtml' ?>
    </body>
</html>