<!DOCTYPE html>
<html>
    <head><?php include '../app/theme/header.phtml' ?></head>
    <body>
        <article class="container">
            <?php include '../app/theme/navigation.phtml' ?>
            <?php include '../app/theme/branding.phtml' ?>
            <h2><?php echo htmlspecialchars($book['title'], ENT_QUOTES, 'UTF-8') ?></h2>
            <h3>By <?php echo htmlspecialchars($book['author'], ENT_QUOTES, 'UTF-8') ?></h3>
            <p>
                <a href="view-book.php?file=<?php echo $book['filename'] ?>"
                   class="media" >
                    <?php echo htmlspecialchars($book['title'], ENT_QUOTES, 'UTF-8') ?>
                </a>
            </p>
            <p>
                <a href="/index.php/books/download/<?php echo (integer) $book['book_id'] ?>">Download book</a>
            </p>
            <p>
                <a href="books.php">Back to books</a>
            </p>
        </article>
        <?php include '../app/theme/scripts.phtml' ?>
        <script type="text/javascript" src="https://raw.githubusercontent.com/malsup/media/master/jquery.media.js"></script>
        <script type="text/javascript" src="https://raw.githubusercontent.com/jquery-orphans/jquery-metadata/master/jquery.metadata.js"></script>
        <script type="text/javascript" src="assets/scripts/book.js"></script>
    </body>
</html>
