<form class="navbar-form navbar-right" role="form" action="/index.php/books/search" method="post">
    <div class="radio">
        <label>Search by</label>
        <label>
            <input type="radio" name="search-type" value="title" class="form-control">Title
        </label>
        <label>
            <input type="radio" name="search-type" value="author" class="form-control">Author
        </label>
    </div>
    <div class="form-group">
        <input type="search" name="book-search" class="form-control">
    </div>
    <div class="form-group">
        <input type="submit" name="search" value="Seacrh" class="btn btn-default">
    </div>
</form>
